version: '3.8'

services:
# SQL Server service
  sql-server:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrong!Passw0rd
      MSSQL_DBNAME: TAI_DB
      MSSQL_PID: Express
    networks:
      - app-network
# .NET API service
  api:
    build:
      context: ./backend/AppDrive/AppDrive.API
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - sql-server
    networks:
      - app-network
# Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge